language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=postgresql-8.3
  - PACKAGE=postgresql-8.4
  - PACKAGE=postgresql-9.0
  - PACKAGE=postgresql-9.1
  - PACKAGE=postgresql-9.2
  - PACKAGE=postgresql-9.3
  - PACKAGE=postgresql-9.4
  - PACKAGE=postgresql-9.5 install_opt='--HEAD'
  - PACKAGE=postgresql-common install_opt='--HEAD'
script:
  - brew install -v $install_opt $PACKAGE
  - brew audit $PACKAGE
  - brew test $PACKAGE
